Vagrant.configure("2") do |config|
	config.vm.define "client" do |client|
        client.vm.box = "generic/debian11"
        client.vm.hostname = "client"
        client.vm.network "private_network", ip: "10.10.20.5"
        client.vm.provider "virtualbox" do |vb|
            vb.memory = 1024
            vb.cpus = 1
        client.vm.synced_folder "config", "/home/vagrant", type: "rsync"
        client.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get install -y apache2-utils nmap
            sudo chmod +x spam.sh
        SHELL
        end
    end
end
