Vagrant.configure("2") do |config|
    config.vm.define "server" do |server|
        server.vm.box = "generic/debian11"
        server.vm.hostname = "server"
        server.vm.network "private_network", ip: "10.10.20.4"
        server.vm.provider "virtualbox" do |vb|
            vb.memory = 2048
            vb.cpus = 2
        server.vm.synced_folder "config", "/home/vagrant", type: "rsync"
        server.vm.provision "shell", inline: <<-SHELL
            sudo apt-get update
            sudo apt-get install -y nginx nginx-extras ufw apache2-utils
            sudo chmod +x config.sh
	    sudo chmod +x index.php
	    sudo chmod +x ufw.sh
        SHELL
        end
    end
end
